### ISSUE TITLE
Elasticsearch version 1.3 is not compatible with Kibana 4

### ISSUE THREAD

**Issue by dexxtreme** [rackspace-cookbooks/elkstack#108]
The default version for Elasticsearch is currently set to 1.3.4, and the default version for Kibana (kibana_lwrp) is 4.0.0-beta3. Kibana 4 does not support Elasticsearch lower than version 1.4. Unless you override the version, you are presented with the following error:

Kibana: This version of Kibana requires Elasticsearch 1.4.0 or higher on all nodes. I found the following incompatible nodes in your cluster: Elasticsearch 1.3.4 @ inet[/xx.xx.xx.xx:9300] (xx.xx.xx.xx)

The default needs to be updated:
https://github.com/rackspace-cookbooks/elkstack/blob/master/attributes/elasticsearch.rb#L3

**Comment by martinb3** [comment]
Kibana 4 has some bugs currently that also need to be fixed, so I think at this point we're recommending people pin back elkstack to before the current major version. We also discovered in testing https://github.com/rackspace-cookbooks/elkstack/pull/104 that Elasticsearch 1.4.x has a data issue where data isn't flowing (tests fail).

**Comment by lmunro** [comment]
:+1:
