### ISSUE TITLE
404 not found as cookbook tries to find a dependency to stack_handler 

### ISSUE THREAD

**Issue by IngoS11** [rackspace-cookbooks/elkstack#123]
Hi guys,
i am pulling the cookbook with librarian-chef and I do get a 404 not found for slack_handler slack handler. not sure which one oft the dependent cookbooks this comes form as it is not in the metadata.rb directly.

Best

Ingo

**Comment by martinb3** [comment]
Hi there -- slack_handler should now be on supermarket. It appears the downstream maintainer never released it. Thanks!
