### ISSUE TITLE
Timeout in Kibana config changed from seconds to milliseconds

### ISSUE THREAD

**Issue by joerg** [rackspace-cookbooks/elkstack#124]
The request_timeout in kibana.yml recently changed from seconds to milliseconds results in errors that no results older than a few minutes can be fetched.
This was also found here: https://github.com/elastic/kibana/issues/3112 and the default value for kibana is now 30000 (https://github.com/elastic/kibana/blob/master/src/server/config/kibana.yml).

**Comment by martinb3** [comment]
@joerg will you try the current master to see if https://github.com/rackspace-cookbooks/elkstack/pull/125 fixed your issue? You may need to enable kibana_workarounds. Thanks!
