### ISSUE TITLE
Custom Logstash input template is not being taken into account by Logstash service

### ISSUE THREAD

**Issue by fabiendelpierre** [rackspace-cookbooks/elkstack#128]
Hi there,
I just tried posting this question in the general Chef mailing list. One of your maintainers, @martinb3 suggested that I post my issue here instead. I'm not actually convinced this is an issue with your cookbook at all, but I have no clue what's going on. 

I'm trying to do a very basic implementation of an Elasticsearch/Logstash/Kibana stack, all running on the same box. I hoped someone had done the hard work of figuring out the mostly undocumented [lusis/chef-logstash](http://github.com/lusis/chef-logstash) cookbook and found the elkstack cookbook. I'm now using it in a very, very vanilla fashion.

Ultimately, I just need Logstash to read an HAProxy log at `/var/log/haproxy.log`. 

I'm using the `elkstack::single` recipe but removed the rsyslog::client include at the end because I don't need it. 

I also don't actually have HAProxy running, just a log file with a few sample entries from an actual HAProxy instance.

Here's what my recipe looks like. The kibana bits are disabled because I don't need them for troubleshooting and it just slows down the provisioning process.
```
include_recipe 'elkstack::_server'
include_recipe 'elkstack::elasticsearch'
include_recipe 'elkstack::logstash'
# node.run_state['elkstack_kibana_username'] = 'kibana'
# node.run_state['elkstack_kibana_password'] = 'kibana'
# include_recipe "elkstack::kibana"

instance_name = node['elkstack']['config']['logstash']['instance_name']

# Create a dummy HAProxy file containing a few entries
template node['cloudmine']['haproxy_log_file'] do
  source "haproxy.log.erb"
  owner "syslog"
  group "adm"
  mode 00644
  not_if { ::File.exist?(node['cloudmine']['haproxy_log_file']) }
  notifies :restart, "logstash_service[#{instance_name}]", :delayed
end
```
At this point, there's nothing set up to tell Logstash to read my HAProxy log file. So I added this simple bit to the recipe:

```
cookbook_file "input_haproxy" do
  path "/opt/logstash/server/etc/conf.d/input_haproxy"
  owner "logstash"
  group "logstash"
  mode 00664
end
```

And this is the content of my input_haproxy file -- I dispensed with any grok filter at this time, just to simplify troubleshooting.
```
input {
  file {
    path => "/var/log/haproxy.log"
    start_position => "beginning"
    type => "haproxy-http"
  }
}
```
If this recipe runs with the `cookbook_file` block and I restart the Logstash service... I get nothing in Elasticsearch, like my HAProxy log file is not being read at all, ever.

However, if I run the recipe without the `cookbook_file` block, SSH into the instance, do a `$ sudo su -l logstash`, manually create the `input_haproxy` file in the correct location (I just start `vi` and copy-paste the contents from the file in my git repo) and assign it the right ownership/permissions, then restart the Logstash service, after about 30 seconds I can see that my HAProxy log was read and I can see it in Elasticsearch, i.e. it's listed under Indices in the Paramedic plugin at [http://33.33.33.10:9200/_plugin/paramedic/](http://33.33.33.10:9200/_plugin/paramedic/) (I'm using Vagrant).

It's incredibly frustrating and I don't understand what I'm doing wrong. It's like Chef does things differently than me when I do it manually, resulting in this silent "failure". I realize Chef does do this a little bit differently, since I believe it would create the file as root during its run and then set the correct permissions, whereas I'm doing it directly as the logstash user... But still, I don't see why this would matter since, in the end, the file is owned by the logstash user, with the `rw-rw-r--` permissions I want. It makes no difference whether I'm using `0664` or `0644`. 

Martin mentioned that a test-kitchen suite would be helpful in troubleshooting this. Unfortunately that's currently beyond my ability to provide. I'm more or less a beginner and haven't had a chance to touch Test Kitchen at all so all my development still happens in Vagrant. I mean to start working with Kitchen ASAP, it just hasn't happened yet. Still, what I'm doing is generic enough that I can show it to you without any issue, if you care to take a closer look, my recipe isn't complex at all and you can feel free to clone [my BitBucket repo](https://bitbucket.org/fabiendelpierre/log-aggregator) and do `$ vagrant up`. The first Vagrant run takes 3.5 minutes on average (on my computer, at least!). I did all my development on a custom Vagrant box (manual Ubuntu 12.04.5 install followed by VirtualBox Guest Additions install) but I just switched to a public Opscode Ubuntu box and tested my code against it, it seems to work fine (beside the issue I'm describing here, which apparently isn't going anywhere yet), so I've updated my Vagrantfile accordingly.

So that's all I can think of... if you know what's going on, any input would be greatly appreciated.

**Comment by martinb3** [comment]
Hi there! When I clone your project and do vagrant up, and then restart logstash and run it from the console, I see log lines flowing:

```
                      "message" => "Mar 1 11:42:38 api3.cm.me haproxy[31165]: 108.242.22.84:4471 [1/Mar/2014:11:42:38.367] sslapi~ api-pool/API_6.1.2 196/0/2/58/256 200 425 - - ---- 186/186/5/0/0 0/0 {0|} {ec59b4bf-edbe} \"GET /v1/app/245008ea0b494bdca5874e80e2bc1c69/search?q=%5B__class__%20%3D%20%22Message%22%2C%20dest%20%3D%20%22agent%22%2C%20custid%20%3D%20%22hlgx9azb%22%2C%20locid%20%3D%20%221%22%5D HTTP/1.1\"",
                     "@version" => "1",
                   "@timestamp" => "2015-04-06T23:48:52.296Z",
                         "type" => "haproxy-http",
                         "host" => "cm-logaggregator",
                         "path" => "/var/log/haproxy.log",
             "syslog_timestamp" => "Mar 1 11:42:38",
                "syslog_server" => "api3.cm.me",
                      "program" => "haproxy",
                          "pid" => "31165",
                    "client_ip" => "108.242.22.84",
                  "client_port" => "4471",
                  "accept_date" => "1/Mar/2014:11:42:38.367",
             "haproxy_monthday" => "1",
                "haproxy_month" => "Mar",
                 "haproxy_year" => "2014",
                 "haproxy_time" => "11:42:38",
                 "haproxy_hour" => "11",
               "haproxy_minute" => "42",
               "haproxy_second" => "38",
         "haproxy_milliseconds" => "367",
                "frontend_name" => "sslapi~",
                 "backend_name" => "api-pool",
                  "server_name" => "API_6.1.2",
                 "time_request" => "196",
                   "time_queue" => "0",
         "time_backend_connect" => "2",
        "time_backend_response" => "58",
                "time_duration" => "256",
             "http_status_code" => "200",
                   "bytes_read" => "425",
      "captured_request_cookie" => "-",
     "captured_response_cookie" => "-",
            "termination_state" => "----",
                      "actconn" => "186",
                       "feconn" => "186",
                       "beconn" => "5",
                      "srvconn" => "0",
                      "retries" => "0",
                    "srv_queue" => "0",
                "backend_queue" => "0",
     "captured_request_headers" => "0|",
    "captured_response_headers" => "ec59b4bf-edbe",
                    "http_verb" => "GET",
                 "http_request" => "/v1/app/245008ea0b494bdca5874e80e2bc1c69/search?q=%5B__class__%20%3D%20%22Message%22%2C%20dest%20%3D%20%22agent%22%2C%20custid%20%3D%20%22hlgx9azb%22%2C%20locid%20%3D%20%221%22%5D",
                 "http_version" => "1.1",
       "input_chef_environment" => "cloudmine_dev",
      "output_chef_environment" => "cloudmine_dev"
}
```

**Comment by fabiendelpierre** [comment]
Thank you very much for your time and trouble. I don't understand what's going on. Simultaneously, in the Chef mailing list, someone asked me to post a debug output of the Chef run, so I was running that while reading your reply, at the end of the run I just go take a look at Paramedic for ****s and giggles, and everything is working... 
I'm [speechless](https://i.imgur.com/sqxNoaY.jpg).

**Comment by fabiendelpierre** [comment]
For what it's worth, I did a `$ vagrant destroy` followed by another `$ vagrant up` and it's not working again. The differences between the time it worked, 30 minutes ago, and this time, were:
- This time, I didn't have the Chef output set to debug
- This time, I had the Vagrant box stored locally, I didn't have to download it

**Comment by fabiendelpierre** [comment]
It gets weirder and weirder... After it worked once (with debug verbosity), failed once again (with normal Chef verbosity), I did a third run, again with debug verbosity, and it's working again...
The one weird thing about running this in debug mode is that about mid-run, it fails with some strange error about a body length not matching an HTTP content length header on the /var/chef/cache/server.tar.gz file, which appears to be the logstash-1.4.2.tar.gz archive. You can see that output after line 2607 of [this gist](https://gist.github.com/anonymous/c9e977d9cc36472abd56#file-gistfile1-txt-L2607).

**Comment by martinb3** [comment]
Hi Fabien,

It looks like someone on the mailing list suggested it might be a proxy issue:
> The root issue in the first instance was a Content-Length mismatch that aborted the download of the logstash tarball (<https://gist.github.com/anonymous/c9e977d9cc36472abd56#file-gistfile1-txt-L2610>). Are you behind a proxy?

Since I can't reproduce the problem, I'm not sure what else to suggest.

**Comment by fabiendelpierre** [comment]
It's not a proxy issue, but yeah, I recognize it's not easy to troubleshoot when you can't reproduce it. I kind of expected that but was hoping it wouldn't work for you either! Oh well. Thanks for trying!
