### ISSUE TITLE
elk stack installation and configuration on centOS 6.6

### ISSUE THREAD

**Issue by ginger8990** [rackspace-cookbooks/elkstack#130]
I could not find a good instruction to install elk stack on centOS 6.6 with latest version of elk.

I was always stopped at configuration part of elk such as creating a new repo.

Anyone know a good web site? I tried these links but not a newer version of ELK.:https://www.digitalocean.com/community/tutorials/how-to-use-logstash-and-kibana-to-centralize-logs-on-centos-6

**Comment by martinb3** [comment]
Hi there -- this repo is for a chef cookbook called 'elkstack', not for the E, L, K, software components themselves. If you're following those tutorials, they cover manually installing the software, not installing through a configuration management tool.

**Comment by martinb3** [comment]
That document that you linked seems reasonable, and should apply to newer versions as well. Hope this helps!

**Comment by ginger8990** [comment]
Anyway, thank you for your reply. I am not a linux admin so don't know so much about chef. The document is reasonable but it is not working for me every time I configure it following the steps. Cannot bring up URL.
