### ISSUE TITLE
logstash hangs after creating logstash_server link

### ISSUE THREAD

**Issue by jperry** [rackspace-cookbooks/elkstack#131]
```
    * link[/etc/init.d/logstash_server] action create
      - create symlink at /etc/init.d/logstash_server to /sbin/sv
    - configure service runit_service[logstash_server]
    * link[/etc/service/logstash_server] action create
      - create symlink at /etc/service/logstash_server to /etc/sv/logstash_server
```

I create a ticket with logstash as well to link the two: https://github.com/lusis/chef-logstash/issues/405

I am running the logstash recipe by itself.  Is it because there is no elasticserach?

Any idea what might be wrong?

**Comment by martinb3** [comment]
Logstash won't start successfully unless it can connect to an elasticsearc (just the way it was written, unfortunately).

**Comment by jperry** [comment]
@martinb3 - I took another look and I am installing using the single.  This is my chef solo file:

```
{
  "run_list": [
    "recipe[elkstack::java]",
    "recipe[elkstack::single]"
  ],
  "automatic": {
    "ipaddress": "52.4.209.76"
  }
}
```

**Comment by martinb3** [comment]
Hi @jperry -- this is very similar to our kitchen test suites. Can you see if those converge for you?

**Comment by jperry** [comment]
@martinb3 - your test kitchen run works but I run into issues where I can't hit 9200 that is port forwarded.  I can hit port 9200 but only on when logged in.  Not sure if there are some iptables blocking things from virtualbox.

**Comment by martinb3** [comment]
@jperry yes, you'll need to login to the box to access Elasticsearch on :9200. We err on the side of caution here, as we see servers in the cloud get compromised before chef even completes, if we make :9200 available.

**Comment by jperry** [comment]
@martinb3 - Is there any way to open this up so I can hit the elasticsearch plugins?  How do you guys access the head plugin?  Do you do port forwarding?

**Comment by martinb3** [comment]
Yes, we usually forward ports. Or configure nginx proxy.

**Comment by martinb3** [comment]
It sounds like the actual stack is working. I'm going to close this since it sounds like there isn't an actual bug there.

**Comment by jperry** [comment]
got it. thanks!  sorry about the confusion.
