### ISSUE TITLE
cron locked to ~> 1.4.3

### ISSUE THREAD

**Issue by promisedlandt** [rackspace-cookbooks/elkstack#161]
Hello,

currently the cron cookbook is locked to version ~> 1.4.3 in metadata.

This makes Berkshelf bork for me, since I use a higher cron version somewhere else.
Looking at the changelog, there are no backwards compatibility breaking changes in cron, and I can run an elkstack fork without a locked cron version fine.

Would it be possible to remove the version lock, or update it to ~> 1.6?

Thanks in advance.

**Comment by martinb3** [comment]
It looks like we pinned it due to https://github.com/opscode-cookbooks/cron/issues/44. I'll unpin it.

**Comment by promisedlandt** [comment]
Thank you!
