### ISSUE TITLE
Fetch elasticsearch network host interface a bit more dynamically

### ISSUE THREAD

**Issue by patcon** [rackspace-cookbooks/elkstack#167]
https://github.com/rackspace-cookbooks/elkstack/blob/master/attributes/elasticsearch.rb#L25

This is currently hardcoded for rackspace, and while a wrapper cookbook can easily fix it, would be nice if it were a bit more dynamic.

Should be able to test for the existence of automatic attr `node['cloud_v2']['local_ipv4']` to determine whether to try to use the private network interface `eth1`, right? (digitalocean doesn't enable this by default)

**Comment by martinb3** [comment]
Seems like the same issue as #52.

**Comment by martinb3** [comment]
I'd definitely like to see us improve on this.

**Comment by patcon** [comment]
Ah thanks. Closing as dup
