### ISSUE TITLE
normal vs default attribute

### ISSUE THREAD

**Issue by phoolish** [rackspace-cookbooks/elkstack#171]
Why is a normal attribute used vs a default attribute on https://github.com/rackspace-cookbooks/elkstack/blob/master/attributes/logstash.rb#L2 ?  Is this due to an upstream cookbook?

**Comment by martinb3** [comment]
Yes, at the time it was due to the upstream cookbook.

**Comment by martinb3** [comment]
There's some major releases pending in elasticsearch (the cookbook) tied to v2.0.0 of Elasticsearch (the software project), but then I'd like to do a big refactor of elkstack to catch it up to the new versions.

**Comment by phoolish** [comment]
That sounds great.  I'd be interested in assisting (especially with the logstash integration) as we use this cookbook pretty extensively in our setup.

**Comment by martinb3** [comment]
@phoolish That would be wonderful! Honestly, we could start any time.

**Comment by martinb3** [comment]
I think we're looking at:
https://github.com/elastic/cookbook-elasticsearch/tree/2.0.0_wip (will be merged to master)
https://github.com/lusis/chef-logstash (master as of now)
https://github.com/lusis/chef-kibana (master as of now)

So I'm thinking we'd bump to those, and then refactor.

**Comment by phoolish** [comment]
That makes sense. Could you also elaborate on #136?

**Comment by martinb3** [comment]
@phoolish I tried to update that. At it's core, it's basically "refactor" so we are doing the interesting work around E, L, and K but not necessarily write custom implementations of things like SSL certificates.

**Comment by phoolish** [comment]
Seems like the right approach.  I'll get started tomorrow.
