### ISSUE TITLE
berkshelf hangs

### ISSUE THREAD

**Issue by patcon** [rackspace-cookbooks/elkstack#173]
Has anyone tried resolving from scratch lately on the newest berkshelf? It seems to be broken in some odd way that I can't quite figure out

https://gist.github.com/patcon/2463a5a6b51ae00436f7

Also happens for really old versions of the cookbook, for resolution via git, and for berkshelf versions as far back as 8.0.1

I'm inclined to suspect it's supermarket, but could use a second set of eyes. Thanks!

**Comment by patcon** [comment]
Hm. Only way I can get it to resolve is to edit the cookbook name elkstack out of the dep graph -- in both metadata.rb name, and in test/fixture/wrapper metadata. If -- say -- just "elkstak" is in the dep graph, then it works fine. Very odd

**Comment by patcon** [comment]
Wierd. Yeah, so changing the cookbook name to elkstack_fork all the metadata.rb files (wrapper and main one) let's resolution complete. But that's the only real way I got it working :/

**Comment by martinb3** [comment]
Have you tried the master revision of berkshelf? It has an option to try different dependency solvers, including a ruby based one. I've been more successful with that one.

**Comment by patcon** [comment]
Ooohh...! Nice. I have not. Thanks! Odd that no one else is mentioning issue though. I should make one last effort to confirm it's an issue even in a clean VM :)

**Comment by patcon** [comment]
Yay! `master` solves it -- no need to even change resolver, so guessing its a resolve v2 fix :)

thanks martin!

**Comment by martinb3** [comment]
:+1:

**Comment by chewi** [comment]
I'm using Berkshelf 4.2.0 (from ChefDK 0.11.2) and I'm still seeing this. It's worth noting that if you add all of elkstack's dependencies directly to a Berksfile but not elkstack itself, it resolves straight away. Very weird.

**Comment by chewi** [comment]
Nevermind, this fixed it.

``` ruby
solver :ruby, :required
```

**Comment by martinb3** [comment]
Yep! Excellent :)
