### ISSUE TITLE
Elkstack logstash-forwarder (AKA lumberjack) SSL auth

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/elkstack#56]
@hhoover It didn’t generate my certificates properly, and after manually putting certificates in place (on the shipper and elk server) would still not work. I ended up writing a very small cookbook to upload a cert and key to the filesystem, which even then could not be verified by logstash-forwarder.

**Comment by martinb3** [comment]
@mrjcleaver Your error is from a change in the default behavior of chef itself. Recently, chef stopped allowing clients to write data bags back to the server by default. I think @hhoover's issue of the cert and key not working even when he added them manually is something else.

**Comment by mrjcleaver** [comment]
Okay, so my issue is continued at https://github.com/rackspace-cookbooks/elkstack/issues/75
