### ISSUE TITLE
Solution constraints can't be solved due to Kibana

### ISSUE THREAD

**Issue by jakekdodd** [rackspace-cookbooks/elkstack#71]
Trying to create a wrapper cookbook for this, and getting the following error upon``berks install``:

```
Unable to satisfy constraints on package kibana due to solution constraint (elkstack = 3.2.1). Solution constraints that may result in a constraint on kibana: [(elkstack = 3.2.1) -> (kibana ~> 1.3)], [(odin-elk = 0.1.0) -> (elkstack = {3.2.1,0.1.1,0.3.0}) -> (kibana ~> 1.3)]
Demand that cannot be met: (elkstack = 3.2.1)
Artifacts for which there are conflicting dependencies: kibana = 0.1.6 -> [(build-essential >= 0.0.0)]Unable to find a solution for demands: elkstack (3.2.1), odin-elk (0.1.0)
```

For reference, here are my Berksfile and metadata.rb:

```ruby
source "https://api.berkshelf.com"

cookbook 'elkstack', github: 'rackspace-cookbooks/elkstack'

metadata
```

```ruby
name             'odin-elk'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures odin-elk'
long_description 'Installs/Configures odin-elk'
version          '0.1.0'

depends 'elkstack'
```

Everything looks OK to me in *your* Berksfile and metadata.rb, so I suspect this is a problem with the Kibana cookbook itself. Not sure why the error message cites a conflicting dependency for Kibana 0.1.6, when the cookbook dependency is locked to 1.3.0. Anybody run into this issue, or have any insights?

**Comment by varh1i** [comment]
not sure if @jakekdodd comment is wrong but this one worked for me in a very similar case

Berksfile

```
source "https://api.berkshelf.com"

cookbook 'kibana', github: 'lusis/chef-kibana', tag: '1.3.0'
cookbook 'elkstack', github: 'rackspace-cookbooks/elkstack'
```
metadata
```
metadata.rb:

depends 'kibana', '1.3.0'
depends 'elkstack'
```

**Comment by martinb3** [comment]
FYI -- the `kibana` cookbook from lusis was recently renamed to `kibana_lwrp` and uploaded to supermarket under that name.

**Comment by martinb3** [comment]
I'm working on a fix now by updating elkstack to use the newer cookbook.
