### ISSUE TITLE
Document hosted chef change that affects data bags

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/elkstack#75]
More information on the change at https://www.getchef.com/blog/2014/11/10/security-update-hosted-chef/. Since elkstack generates and saves a key/cert for the lumberjack protocol, it is likely affected.

**Comment by mrjcleaver** [comment]
Would it be fair to say that implementing (from that post):

> Using knife-acl plugin
>
> knife acl add containers data update group clients
>
> If you have cookbooks that are creating or deleting data bags or data bag items, you will also need to add ‘create’ and ‘delete’ permissions respectively:
>
> knife acl add containers data create group clients
> knife acl add containers data delete group clients

Will work? Is there a minimal version that grants only exactly what elkstack needs?

Thanks Martin.

**Comment by mrjcleaver** [comment]
Also, might be worth mentioning that I was using Open Source Chef 11.x, not Hosted Chef.

**Comment by marcantonio** [comment]
I also ran into this issue using open source chef 11.x.

**Comment by martinb3** [comment]
We no longer try to write to a data bag by default.
