### ISSUE TITLE
Issues when updating kibana

### ISSUE THREAD

**Issue by lil-cain** [rackspace-cookbooks/elkstack#95]
If moving a system between 1.3.x versions, this cookbook fails to converge. This is as the kibana install doesn't referesh the file in https://github.com/lusis/chef-kibana/blob/KIBANA3/provider/install.rb#L60. Unfortunately, the symlink *is* changed, as this does include the kibana version
https://github.com/lusis/chef-kibana/blob/KIBANA3/providers/install.rb#L75-L76. This then results in a failure as https://github.com/rackspace-cookbooks/elkstack/blob/master/recipes/kibana.rb#L55 fails (as the 'curren't symlink' is broken).

**Comment by martinb3** [comment]
I believe this is resolved through the newest version, as kibana is deployed differently now. If this is still an issue with the newer version, we'll need to report it upstream. Please let me know if we need to do that, and I'll chase it with upstream. Thank you for the report!
